### PR TITLE
OU-499: Port CONSOLE-4124, ODC-7655, CONSOLE-4127 to dynamic plugin

### PR DESCRIPTION
**Pull request by logonoff**
https://issues.redhat.com/browse/OU-499

port from
- https://github.com/openshift/console/pull/14138
- https://github.com/openshift/console/pull/14247
- https://github.com/openshift/console/pull/14157

Also migrated `KebabDropdown`:

https://github.com/user-attachments/assets/23da9ba0-089d-4a33-8a55-df2f7ae31f86

What changed:
- Metrics:
	- Timespan dropdown image
	- All kebab menus image
- Monitoring Dashboard:
	- Dashboard selector image
	- All kebab menus image
- Create silence form
 	- Silence for dropdown image

### CODE REVIEW

**Comment by zhuje** [comment]
/cc @juzhao 

Could you test this?

**Comment by juzhao** [comment]
tested with PR, 
`launch 4.19,openshift/monitoring-plugin#282 aws`
no issue, but found 2 regression bugs **not** caused by this PR
https://issues.redhat.com/browse/OCPBUGS-45801
https://issues.redhat.com/browse/OCPBUGS-45816
/label qe-approved

**Pull request merged**
