### PR TITLE
OU-561: Use AlertsRulesDetailPage from `monitoring-plugin`

### PR DESCRIPTION
**Pull request by logonoff**
/hold

https://github.com/openshift/console/pull/14596
https://github.com/openshift/monitoring-plugin/pull/286

**Fixes**: 

https://issues.redhat.com/browse/CONSOLE-4380
https://issues.redhat.com/browse/OU-561

**Solution Description**: 

- Remove `AlertRulesDetailsPage` from console
- Add a route in monitoring-plugin to enable it
- Remove code related to routes that are no longer provided by console repo

**Screen shots / Gifs for design review**: 

image

The only change to the AlertsRulesDetailPage in the developer perspective is that it will no longer have a namespace selector. Since the selected alert is already namespaced, it didn't make sense to swap namespaces while focused on a specific AlertRule.

**Unit test coverage report**: 

n/a

**Test setup:**

Host the monitoring dynamic plugin locally by running
```sh
./bin/bridge -plugins monitoring-plugin=http://localhost:9001 -i18n-namespaces=plugin__monitoring-plugin -branding openshift  # console backend
yarn dev  # console/frontend and monitoring-plugin/web
```

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari

### CODE REVIEW

**Comment by zhuje** [comment]
/cc @juzhao 

Can you test this with https://github.com/openshift/console/pull/14596?

All the functionality of the Alert Details Page should be the same. We're just migrating the code from openshift/console to the monitoring-plugin. 

This PR in the console removes the Alert Details Page https://github.com/openshift/console/pull/14596. 
While this PR adds the code for the Alert Details Page for the monitoring-plugin.

**Comment by zhuje** [comment]
Once QE reviews it. I'll mark it with LGTM.

**Comment by juzhao** [comment]
tested with cluster-bot
`launch 4.19,openshift/monitoring-plugin#286,openshift/console#14596 aws`

found 3 regression bugs, not related to these 2 PRs
https://issues.redhat.com/browse/OCPBUGS-37547
https://issues.redhat.com/browse/OCPBUGS-45892
https://issues.redhat.com/browse/OCPBUGS-45896

**Pull request merged**
