### PR TITLE
OCPBUGS-42845: Fix Dashboard/Metrics Drop-Downs 

### PR DESCRIPTION
**Pull request by zhuje**
## Related JIRA: 
[OCPBUGS-42845](https://issues.redhat.com/browse/OCPBUGS-42845) Clicking some dropdown list doesn't take effect on Dashboard/Metrics page

## Description 
The dropdowns for `Time Range` and `Refresh Interval` on the Dashboard page are not functional in OCP v4.18. This PR fixes the dropdowns to restore functionality. 

### Before 
OCPBUGS-42845_Admin_Before
OCPBUGS-42845_Dev_Before

### After
OCPBUGS-42845_Admin_After
Figure 3. Administrator Perspective > Observe > Dashboards. Time Range and Refresh Interval dropdowns are functional. 

OCPBUGS-42845_Dev_After
Figure 4. Developer Perspective > Observe > Dashboards. Time Range and Refresh Interval dropdowns are functional.

### CODE REVIEW

**Comment by zhuje** [comment]
/hold 

After the code review, I'll reach out to QE. 
After QE approval, I'll unhold.

**Comment by juzhao** [comment]
/label qe-approved
tested with PR, "Time Range" and "Refresh Interval" drop-down list works well, no error

**Comment by zhuje** [comment]
/unhold 

Because QE approval and code review.

**Pull request merged**
