### PR TITLE
OCPBUGS-43239: upgrade dynamic plugin sdk to remove vulnerable dependencies 4.16

### PR DESCRIPTION
**Pull request by jgbernalp**
This PR

- updates the dynamic plugin sdk to remove vulnerable dependencies
- updates other vulnerable dependencies directly

This PR is done directly to release-4.16 as the sdk dependency support varies for 4.16

### CODE REVIEW

**Comment by jgbernalp** [comment]
/hold
until QE checks

**Comment by Tai-RedHat** [comment]
PR tested with cluster-bot, monitoring-plugin worked well
/label qe-approved

**Pull request merged**
