### PR TITLE
OU-431: Export CSV for Alert Tables

### PR DESCRIPTION
**Pull request by zhuje**
Formats Alert data into comma-separated values string and passes it to <VirtualizedTable> so it can be exported. 

https://github.com/user-attachments/assets/4064daf3-59c3-4b9e-9aff-0f5d964d9a07

<b>HOLD</b>: The changes needed for the Virtualized table to support an export CSV button is found here:   https://github.com/openshift/console/pull/14050. We are awaiting the merge/release of the feature. Then, we can upgrade the monitoring-plugin's `package.json` .

### CODE REVIEW

**Comment by jgbernalp** [comment]
https://github.com/openshift/console/pull/14050 needs to be merged first so we can use this new prop

**Comment by juzhao** [comment]
tested along with the 2 PRs
`launch 4.17.0-0.nightly-2024-07-31-220437,openshift/console#14050,openshift/monitoring-plugin#133 aws`
can not get a successful cluster, error is: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/release-openshift-origin-installer-launch-aws-modern/1819207722529198080
```
 ERRO[2024-08-02T03:35:00Z] 
  * could not run steps: step monitoring-plugin failed: error occurred handling build monitoring-plugin-amd64: the build monitoring-plugin-amd64 failed after 7m2s with reason DockerBuildFailed: Dockerfile build strategy has failed. 
 ```
same error as mentioned in https://github.com/openshift/monitoring-plugin/pull/133#issuecomment-2257697958 for the failed ci/prow/images job: [https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_moni[…]penshift-monitoring-plugin-main-images/1818190428122386432](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_monitoring-plugin/133/pull-ci-openshift-monitoring-plugin-main-images/1818190428122386432). then will continue to test https://github.com/openshift/monitoring-plugin/pull/133  after https://github.com/openshift/console/pull/14050 merged

**Pull request merged**
