### PR TITLE
NO-JIRA: Update query-browser to not use setState

### PR DESCRIPTION
**Pull request by zhuje**

### CODE REVIEW

**Comment by jgbernalp** [comment]
@zhuje it seems we are also missing the query input adjustments

**Comment by lihongyan1** [comment]
@juzhao @Tai-RedHat Please take care of the PR

**Comment by juzhao** [comment]
@Tai-RedHat please help to check

**Comment by Tai-RedHat** [comment]
PR tested with cluster-bot
/label qe-approved

**Pull request merged**
