### PR TITLE
OCPBUGS-43238: upgrade dynamic plugin sdk to remove vulnerable dependencies 4.17

### PR DESCRIPTION
**Pull request by jgbernalp**
This PR 

- updates the dynamic plugin sdk to remove vulnerable dependencies
- updates other vulnerable dependencies directly

This PR is done directly to `release-4.17` as the dependency does not exists anymore in 4.18

### CODE REVIEW

**Comment by jgbernalp** [comment]
/hold
until QE checks

**Comment by Tai-RedHat** [comment]
PR tested with cluster-bot, monitoring-plugin worked well
/label qe-approved

**Pull request merged**
